## Numpy array operations

In [1]:
import numpy as np 

In [14]:
arr = np.arange(10)
#slicing
print("Array", arr)
print("Baisc slicing", arr[2:7])
# step slicing
print("Step slicing" , arr[2:8:2])

#negative slicing
print("Negative slicing" , arr[-2])


Array [0 1 2 3 4 5 6 7 8 9]
Baisc slicing [2 3 4 5 6]
Step slicing [2 4 6]
Negative slicing 8



## Two dimensional array slicing

In [20]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array", array_2d)
#specific element
print("Specific element" , array_2d[1 ,2])
# target entire row
print("Entire row " , array_2d[1] )

#target entire column
print("Entire column" , array_2d[: , 2])

2D array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element 6
Entire row  [4 5 6]
Entire column [3 6 9]


### Sorting

In [24]:
unsorted_Array = np.array([1,3,2,5,4,6,7,8,9])
print("Unsorted array", unsorted_Array)
#sorting
print("Sorted array" , np.sort(unsorted_Array))

#sorting 2D array
unsorted_2d_array = np.array([[1,4,2],[3,1,5],[7,8,6]])
print("Unsorted 2D array", unsorted_2d_array)
print("Sorted 2D array" , np.sort(unsorted_2d_array , axis=0))

Unsorted array [1 3 2 5 4 6 7 8 9]
Sorted array [1 2 3 4 5 6 7 8 9]
Unsorted 2D array [[1 4 2]
 [3 1 5]
 [7 8 6]]
Sorted 2D array [[1 1 2]
 [3 4 5]
 [7 8 6]]


## Filter

In [25]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers", even_numbers)

Even numbers [2 4 6 8]


### Filter with mask

In [27]:
mask = numbers > 3
print("Mask" , mask)
print("Masked numbers" , numbers[mask])

Mask [False False False  True  True  True  True  True  True]
Masked numbers [4 5 6 7 8 9]


### Fancy indexing vs np.where()

In [ ]:
indices = [0,3,5]
print("numbers at indices" , numbers[indices])

nums = np.array([1,2,3,4,5,6,7,8,9])
# where function
where_result = np.where(nums > 3)
print("Where result " , nums[where_result])

#condition array means if the condition is true then multiply the number by 2 else keep the number as it is
condition_array = np.where(nums > 3 , nums*2 , nums)
print("Condition array" , condition_array)

numbers at indices [100 100 100]
Where result  [4 5 6 7 8 9]
Condition array [ 1  2  3  8 10 12 14 16 18]


### Merging , array compatiblity

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
#concatenation
print("Concatenation" , np.concatenate((arr1,arr2)))

#stacking means stacking the arrays on top of each other or side by side 
print("Stacking" , np.stack((arr1,arr2)))

#compatiblity shapes
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibilty shapes" ,a.shape == b.shape == c.shape)

Concatenation [ 1  2  3  4  5  6  7  8  9 10]
Stacking [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Compatibilty shapes True
