## Numpy Basics

In [3]:
import numpy as np


### numpy arrays

In [5]:
arr_1d = np.array([1,2,3,4,5])
print("one Dimensional array" , arr_1d)

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print("Two Dimensional array" , arr_2d)

one Dimensional array [1 2 3 4 5]
Two Dimensional array [[1 2 3 4]
 [5 6 7 8]]


### List vs Numpy Array

In [ ]:
py_list = [1,2,3,4,5]
print("Python list multiplication" , py_list*2) # list multiplication

np_array = np.array([1,2,3,4,5,6])
print("Numpy array multiplication" , np_array*2)  # element wise multiplication

Python list multiplication [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication [ 2  4  6  8 10 12]


In [11]:
import time
start = time.time()

py_List = [i*2 for i in range(100000)]
print(" \n Time taken for python list multiplication" , time.time()-start)

start = time.time()
np_array = np.arange(10000)*2
print(" \n Time taken for numpy array multiplication" , time.time()-start)

 
 Time taken for python list multiplication 0.017306089401245117
 
 Time taken for numpy array multiplication 0.005015850067138672


### creating arrays from scratch in numpy

In [21]:
zeros_array = np.zeros((3,4)) # 3 rows and 4 columns
print("\n Zeros array" , zeros_array)

ones_array = np.ones((4,5)) # 4 rows and 5 columns
print("\n Ones array" , ones_array)

full_array = np.full((3,4) ,9) # full array means all elements are same in the array like 9
print("\n Full array" , full_array)

random = np.random.random((3,6)) # random array of 3 rows and 6 columns
print("\n Random array" , random)

sequence_array = np.arange(2,20,2) # start from 2 and end at 20 with step of 2
print("\n Sequence array" , sequence_array)


 Zeros array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Ones array [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 Full array [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]

 Random array [[0.46986317 0.02378964 0.04985042 0.32665278 0.20796553 0.70830427]
 [0.28189118 0.14179903 0.72403708 0.26638835 0.26259174 0.69905793]
 [0.04899817 0.80951869 0.44301147 0.89350939 0.46189442 0.59229665]]

 Sequence array [ 2  4  6  8 10 12 14 16 18]


## VECTOR MATRICES AND TENSOR 

In [24]:
# vector 
vector = np.array([1,2,3,4,])
print("\n Vector" , vector)

# matrix
matrix = np.array([[1,2,3,4], [5,6,7,8]])
print("\n Matrix" , matrix)

#tensor 
tensor = np.array([[[1,2,3,4],[5,6,7,8]],
                   [[9,10,11,12],[13,14,15,16]]]) # tesnor of 2x2x4 that means 2 matrix of 2x4 multi dimensional array 
print("\n Tensor" , tensor)


 Vector [1 2 3 4]

 Matrix [[1 2 3 4]
 [5 6 7 8]]

 Tensor [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


### Array Properties

In [30]:
arr = np.array([[1,2,3,],
                [4,5,6]])
#shape of array
print("\n Shape of array" , arr.shape)

#size of array
print("\n Size of array" , arr.size)

#dimension of array
print("\n Dimension of array" , arr.ndim)

#data type of array
print("\n Data type of array" , arr.dtype)

#total number of elements in array
print("\n Total number of elements in array" , arr.nbytes) # how 48 elements in this array 1 byte = 8 bits 




 Shape of array (2, 3)

 Size of array 6

 Dimension of array 2

 Data type of array int64

 Total number of elements in array 48


### Array reshapping

In [38]:
arr = np.arange(12)
print("\n  Original Array" , arr)

## reshaping the array

reshaped_array = arr.reshape(3,4)
print("\n Reshaped Array" , reshaped_array)

## flatten the array
flattened_array = reshaped_array.flatten()
print("\n Flattened Array" , flattened_array)

## transpose the array means rows will become columns and columns will become rows
transposed_array = reshaped_array.T
print("\n Transposed Array" , transposed_array)

## ravels the array means convert the array into one dimensional array just like flatten but it is not a copy of the array it is the view of the array 
raveled_array = reshaped_array.ravel()
print("\n Raveled Array" , raveled_array)


  Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

 Raveled Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
